join:
  description: Group players together.
  fields:
    master:
      description: Entity ID of the player to synchronize to.
      example: 'media_player.living_room'
    entity_id:
      description: Entity ID of the players to join to the "master".
      example: 'media_player.bedroom'

unjoin:
  description: Unjoin the player from a group.
  fields:
    entity_id:
      description: Entity ID of the player to unjoin.
      example: 'media_player.living_room'

snapshot:
  description: Take a snapshot of the media player.
  fields:
    entity_id:
      description: Name(s) of entities that will be snapshotted. Platform dependent.
      example: 'media_player.living_room'

restore:
  description: Restore a snapshot of the media player.
  fields:
    entity_id:
      description: Name(s) of entities that will be restored. Platform dependent.
      example: 'media_player.living_room'
